title: Benchmarking Reconstruction Methods for Bundle Segmentation: Preparing for Clinical Translation
# logo: logo.png
description: |
  A short description of the project.
theme: minima
plugins:
  - jekyll-seo-tag
